class_name BluetoothConstants

static var CHARACTERISTIC_PROPERTY_BROADCAST : int = 0x0001
static var CHARACTERISTIC_PROPERTY_READ : int = 0x0002
static var CHARACTERISTIC_PROPERTY_WRITE_NO_RESPONSE : int = 0x0004
static var CHARACTERISTIC_PROPERTY_WRITE : int = 0x0008
static var CHARACTERISTIC_PROPERTY_NOTIFY : int = 0x0010
static var CHARACTERISTIC_PROPERTY_INDICATE : int = 0x0020
static var CHARACTERISTIC_PROPERTY_AUTHENTICATED_SIGNED_WRITES : int = 0x0040
static var CHARACTERISTIC_PROPERTY_EXTENDED_PROPERTIES : int = 0x0080